# For more information: https://laravel.com/docs/sail
version: '3'
volumes:
    mongo-data:
services:
    front:
        image: front
        container_name: front_container
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
                PORT: ${PORT}
                BACK_API_PORT: ${BACK_API_PORT}
        ports:
            - "${PORT}:${PORT}"
        env_file:
            - .env
        environment:
            BACK_API_PORT: ${BACK_API_PORT}
            PORT: ${PORT}
        links:
            - back_api
        depends_on:
            - back_api
    back_api:
        image: back_api
        container_name: back_api_container
        build:
            context: ./back
            dockerfile: Dockerfile
            args:
                BACK_API_PORT: ${BACK_API_PORT}
        ports:
            - "${BACK_API_PORT}:${BACK_API_PORT}"
        env_file:
            - .env
        environment:
            BACK_API_PORT: ${BACK_API_PORT}
            PASSWORD_TOKEN_KEY: ${PASSWORD_TOKEN_KEY}
            SESSION_TOKEN_KEY: ${SESSION_TOKEN_KEY}
        links:
            - monguito
        depends_on:
            - monguito
    monguito:
        image: mongo
        restart: always
        ports:
          - "27017:27017"
